/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SuperAdminAuditRouteImport } from './routes/super-admin.audit'
import { Route as SuperAdminOrganisationsRouteImport } from './routes/super-admin.organisations'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAuditRoute = SuperAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminOrganisationsRoute = SuperAdminOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/organisations': typeof SuperAdminOrganisationsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/organisations': typeof SuperAdminOrganisationsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/organisations': typeof SuperAdminOrganisationsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/invitations'
    | '/login'
    | '/organizations'
    | '/signup'
    | '/super-admin'
    | '/super-admin/audit'
    | '/super-admin/organisations'
    | '/super-admin/users'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/invitations'
    | '/login'
    | '/organizations'
    | '/signup'
    | '/super-admin'
    | '/super-admin/audit'
    | '/super-admin/organisations'
    | '/super-admin/users'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/invitations'
    | '/login'
    | '/organizations'
    | '/signup'
    | '/super-admin'
    | '/super-admin/audit'
    | '/super-admin/organisations'
    | '/super-admin/users'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  SignupRoute: typeof SignupRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/audit': {
      id: '/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof SuperAdminAuditRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/organisations': {
      id: '/super-admin/organisations'
      path: '/organisations'
      fullPath: '/super-admin/organisations'
      preLoaderRoute: typeof SuperAdminOrganisationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminAuditRoute: typeof SuperAdminAuditRoute
  SuperAdminOrganisationsRoute: typeof SuperAdminOrganisationsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAuditRoute: SuperAdminAuditRoute,
  SuperAdminOrganisationsRoute: SuperAdminOrganisationsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  SignupRoute: SignupRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
