/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as QuestionsQuestionIdRouteImport } from './routes/questions/$questionId'
import { Route as QuestionsNewRouteImport } from './routes/questions/new'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdRoute = QuestionsQuestionIdRouteImport.update({
  id: '/questions/$questionId',
  path: '/questions/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsNewRoute = QuestionsNewRouteImport.update({
  id: '/questions/new',
  path: '/questions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/workspace/settings',
  path: '/workspace/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/questions/$questionId'
    | '/questions/new'
    | '/workspace/settings'
    | '/admin/'
    | '/questions/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/questions/$questionId'
    | '/questions/new'
    | '/workspace/settings'
    | '/admin'
    | '/questions'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/questions/$questionId'
    | '/questions/new'
    | '/workspace/settings'
    | '/admin/'
    | '/questions/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  QuestionsQuestionIdRoute: typeof QuestionsQuestionIdRoute
  QuestionsNewRoute: typeof QuestionsNewRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId': {
      id: '/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof QuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/new': {
      id: '/questions/new'
      path: '/questions/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof QuestionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/workspace/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  QuestionsQuestionIdRoute: QuestionsQuestionIdRoute,
  QuestionsNewRoute: QuestionsNewRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
